apiVersion: v1
kind: Service
metadata:
  name: split-bill-be-service
spec:
  selector:
    app: split-bill-be
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
