// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/billmembers": {
            "get": {
                "description": "Get all Bill Members",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billmembers"
                ],
                "summary": "Get all Bill Members",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.BillMember"
                            }
                        }
                    },
                    "404": {
                        "description": "Page not found",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: Server failed to process the request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new bill member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billmembers"
                ],
                "summary": "Create a new bill member",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BillMember"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BillOwner"
                        }
                    },
                    "404": {
                        "description": "Page not found",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: Server failed to process the request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    }
                }
            }
        },
        "/billmembers/{id}": {
            "get": {
                "description": "Get a bill member by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billmembers"
                ],
                "summary": "Get a bill member by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.BillMember"
                            }
                        }
                    },
                    "404": {
                        "description": "Page not found",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: Server failed to process the request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Edit Bill Member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billmembers"
                ],
                "summary": "Edit Bill Member",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BillMember"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BillOwner"
                        }
                    },
                    "404": {
                        "description": "Page not found",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: Server failed to process the request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a bill member by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billmembers"
                ],
                "summary": "Delete a bill member by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BillOwner"
                        }
                    },
                    "404": {
                        "description": "Page not found",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: Server failed to process the request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    }
                }
            }
        },
        "/billowners": {
            "get": {
                "description": "Get all Bill Owner",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billowners"
                ],
                "summary": "Get all Bill Owner",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.BillOwner"
                            }
                        }
                    },
                    "404": {
                        "description": "Page not found",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: Server failed to process the request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new bill owner",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billowners"
                ],
                "summary": "Create new bill owner",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BillOwner"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BillOwner"
                        }
                    },
                    "404": {
                        "description": "Page not found",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: Server failed to process the request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    }
                }
            }
        },
        "/billowners/{id}": {
            "get": {
                "description": "Get Bill Owner by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billowners"
                ],
                "summary": "Get a Bill Owner by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.BillOwner"
                            }
                        }
                    },
                    "404": {
                        "description": "Page not found",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: Server failed to process the request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Edit Bill Owner",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billowners"
                ],
                "summary": "Edit Bill Owner",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BillOwner"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BillOwner"
                        }
                    },
                    "404": {
                        "description": "Page not found",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: Server failed to process the request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete bill owner by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billowners"
                ],
                "summary": "Delete bill owner by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BillOwner"
                        }
                    },
                    "404": {
                        "description": "Page not found",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: Server failed to process the request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    }
                }
            }
        },
        "/bills": {
            "get": {
                "description": "Get all Bills from table",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bills"
                ],
                "summary": "Get all bills",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Bill"
                            }
                        }
                    },
                    "404": {
                        "description": "Page not found",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: Server failed to process the request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new bill",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bills"
                ],
                "summary": "Create a new bill",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Bill"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Bill"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Page not found",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: Server failed to process the request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    }
                }
            }
        },
        "/bills/{id}": {
            "get": {
                "description": "Get bill by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bills"
                ],
                "summary": "Get a bill by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Bill"
                        }
                    },
                    "404": {
                        "description": "Page not found",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: Server failed to process the request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update bill by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bills"
                ],
                "summary": "Update a bill by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Bill"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Bill"
                        }
                    },
                    "404": {
                        "description": "Page not found",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: Server failed to process the request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete bill by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bills"
                ],
                "summary": "Delete a bill by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    },
                    "404": {
                        "description": "Page not found",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error: Server failed to process the request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "helpers.ErrResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.Bill": {
            "type": "object",
            "properties": {
                "bill_owner_id": {
                    "description": "belongs to a BillOwner",
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "raw_image": {
                    "type": "string"
                }
            }
        },
        "models.BillMember": {
            "type": "object",
            "properties": {
                "bill_id": {
                    "description": "belongs to a Bill",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "price_owe": {
                    "type": "number"
                }
            }
        },
        "models.BillOwner": {
            "type": "object",
            "properties": {
                "bank_account": {
                    "type": "string"
                },
                "contact": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Split Bill API",
	Description:      "Split Bill Swagger Documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
