basePath: /api/v1
definitions:
  helpers.ErrResponse:
    properties:
      message:
        type: string
    type: object
  models.Bill:
    properties:
      bill_owner_id:
        description: belongs to a BillOwner
        type: integer
      id:
        type: string
      name:
        type: string
      raw_image:
        type: string
    type: object
  models.BillOwner:
    properties:
      bank_account:
        type: string
      contact:
        type: string
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Split Bill Swagger Documentation
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Split Bill API
  version: "1.0"
paths:
  /billowners:
    get:
      description: Get all Bill Owner
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.BillOwner'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helpers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.ErrResponse'
      summary: Get all Bill Owner
      tags:
      - billowners
    post:
      consumes:
      - application/json
      description: Create new bill owner
      parameters:
      - description: Bill Owner data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.BillOwner'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BillOwner'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helpers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.ErrResponse'
      summary: Create new bill owner
      tags:
      - billowners
  /billowners/{id}:
    delete:
      description: Delete bill owner by ID
      parameters:
      - description: Bill Owner ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BillOwner'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helpers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.ErrResponse'
      summary: Delete bill owner by ID
      tags:
      - billowners
    get:
      description: Get Bill Owner by ID
      parameters:
      - description: data
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.BillOwner'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helpers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.ErrResponse'
      summary: Get a Bill Owner by ID
      tags:
      - billowners
    put:
      consumes:
      - application/json
      description: Edit Bill Owner
      parameters:
      - description: Bill Owner ID
        in: path
        name: id
        required: true
        type: integer
      - description: Edit Bill Owner Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.BillOwner'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BillOwner'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helpers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.ErrResponse'
      summary: Edit Bill Owner
      tags:
      - billowners
  /bills:
    get:
      description: Get all Bills from table
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Bill'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.ErrResponse'
      summary: Get all bills
      tags:
      - bills
    post:
      consumes:
      - application/json
      description: Create a new bill
      parameters:
      - description: Bill Data
        in: body
        name: bill
        required: true
        schema:
          $ref: '#/definitions/models.Bill'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Bill'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.ErrResponse'
      summary: Create a new bill
      tags:
      - bills
  /bills/{id}:
    delete:
      description: Delete bill by ID
      parameters:
      - description: Bill ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.ErrResponse'
      summary: Delete a bill by ID
      tags:
      - bills
    get:
      description: Get bill by ID
      parameters:
      - description: Bill ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Bill'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helpers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.ErrResponse'
      summary: Get a bill by ID
      tags:
      - bills
    put:
      description: Update bill by ID
      parameters:
      - description: Bill ID
        in: path
        name: id
        required: true
        type: string
      - description: Bill Data
        in: body
        name: bill
        required: true
        schema:
          $ref: '#/definitions/models.Bill'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Bill'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.ErrResponse'
      summary: Update a bill by ID
      tags:
      - bills
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
